### ISSUE TITLE
Sanitizer is broken, Unknown parameter inline style

### ISSUE THREAD

**Issue by inkhey** [matthiask/html-sanitizer#1]
Sanitize just don't work in my own instance. wiith python 3.5.3, html-sanitizer 1.3.0, lxml 3.6.0 and
beautifulsoup4 4.4.0 .

 ```
 File "***", line 63, in get_body
    body = sanitizer.sanitize('')
  File "**/tg2env/lib/python3.5/site-packages/html_sanitizer/sanitizer.py", line 141, in sanitize
    add_nofollow=self.add_nofollow,
  File "**/tg2env/lib/python3.5/site-packages/lxml/html/clean.py", line 216, in __init__
    "Unknown parameter: %s=%r" % (name, value))
TypeError: Unknown parameter: inline_style=False
```

**Comment by matthiask** [comment]
Oh yeah, it seems that I didn't specify the supported lxml versions closely enough.

Are you stuck on lxml 3.6 or is it possible to upgrade? I'm not completely sure which lxml version is supported (but I'll find out now!)

**Comment by matthiask** [comment]
https://github.com/lxml/lxml/commit/12b93e23e8447a03ab592b30406ae85406d150c3

`inline_style` should be supported starting with 3.6.1.

**Comment by matthiask** [comment]
This issue has been fixed in https://github.com/matthiask/html-sanitizer/commit/ac3f83ba2b22d90d701ae9acf3eb334122ba6413
