### ISSUE TITLE
the non-closed tag should not be discarded completely

### ISSUE THREAD

**Issue by akhalil-xiq** [matthiask/html-sanitizer#19]
from html_sanitizer import Sanitizer

sanitizer = Sanitizer()
sanitizer.sanitize('<task < type < date')

and the result was an empty string. It should return the string.

**Comment by matthiask** [comment]
html-sanitizer uses `lxml.html.clean.Cleaner` under the hood:

![image](https://user-images.githubusercontent.com/2627/86561186-62963c00-bf60-11ea-96a8-edcba30f2076.png)

I don't think there's anything we can do here. Where does this string come from? And what do browsers do with this? `<` starts a tag, `<task>`, `<type>` and `<date>` are AFAIK no official HTML tags so it makes some sense to me that `Cleaner()` would remove them from the result.

**Comment by akhalil-xiq** [comment]
> html-sanitizer uses `lxml.html.clean.Cleaner` under the hood:
> 
> ![image](https://user-images.githubusercontent.com/2627/86561186-62963c00-bf60-11ea-96a8-edcba30f2076.png)
> 
> I don't think there's anything we can do here. Where does this string come from? And what do browsers do with this? `<` starts a tag, `<task>`, `<type>` and `<date>` are AFAIK no official HTML tags so it makes some sense to me that `Cleaner()` would remove them from the result.

basically, I was trying to use this package to sanitize the input to avoid XSS.

**Comment by matthiask** [comment]
Yes that it one of the intended uses of this library. 

However, it's really only useful to sanitize HTML. If you submit plaintext it will not work well.
