### ISSUE TITLE
Test failures due to extraneous end tags

### ISSUE THREAD

**Issue by Ikke** [matthiask/html-sanitizer#20]
* python 3.9.5
* html-sanitizer 1.9.1
* lxml 4.6.3

When running the test suite, we get summarized:

```
Ran 26 tests in 0.065s

FAILED (failures=87)
Test failed: <unittest.runner.TextTestResult run=26 errors=0 failures=87>
```

The issue is that `lxml.html.clean.Cleaner` appends `</div></body></html>\n` to all output.

For example:

```python
AssertionError: ' </div></body></html>\n' != ' '
-  </div></body></html>
+   : Cleaning 'b'<p>&nbsp;</p>'', expected 'b' '' but got 'b' </div></body></html>\\n''
```

This would fix all unittests, but I guess it's more like a work-around than a real fix:

```diff
diff --git a/html_sanitizer/tests.py b/html_sanitizer/tests.py
index abeb294..feb902c 100644
--- a/html_sanitizer/tests.py
+++ b/html_sanitizer/tests.py
@@ -18,8 +18,12 @@ class SanitizerTestCase(TestCase):
     def run_tests(self, entries, sanitizer=Sanitizer()):
         for before, after in entries:
             with self.subTest(before=before, after=after):
+                suffix = "</div></body></html>\n"
                 after = before if after is None else after
                 result = sanitizer.sanitize(before)
+                if result.endswith(suffix):
+                    result = result[0:-len(suffix)]
+
                 self.assertEqual(
                     result,
                     after,
```

**Comment by matthiask** [comment]
Thanks for the report! That's very strange and I cannot reproduce this with my local version (Python 3.9.0+, same versions of lxml etc.)

I wonder what's going on there. The output seems to be completely broken. I have restarted the last build, maybe the failure is reproducable there. https://github.com/matthiask/html-sanitizer/actions/runs/789537893

**Comment by Ikke** [comment]
So I guess this is an issue with lxml? Small reproduction:

```python
import lxml.html.clean
d = lxml.html.fromstring('<div><strong>This is <em>a</em> message</strong></div>')
lxml.html.clean.Cleaner(remove_unknown_tags=False, style=True, safe_attrs_only=False, inline_style=False, forms=False)(d)
print(lxml.html.tostring(d, encoding='unicode'))
```
result:
```
<div><strong>This is <em>a</em> message</strong></div></body></html>
```

So it appends `</body></html>`

**Comment by matthiask** [comment]
Thanks! When I run this the output looks as follows:

```
[22.05. 21:31:32] ~/Projects/html-sanitizer$ .tox/py39/bin/python
Python 3.9.0+ (default, Oct 19 2020, 09:51:18)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml.html.clean
.html.fromstring('<div><strong>This is <em>a</em> message</strong></div>')
lxml.html.clean.Cleaner(remove_unknown_tags=False, style=True, safe_attrs_only=False, inline_style=False, forms=False)(d)>>> d = lxml.html.fromstring('<div><strong>This is <em>a</em> message</strong></div>')
>>> lxml.html.clean.Cleaner(remove_unknown_tags=False, style=True, safe_attrs_only=False, inline_style=False, forms=False)(d)
None
>>> print(lxml.html.tostring(d, encoding='unicode'))
<div><strong>This is <em>a</em> message</strong></div>
None
>>>
```

Are you installing lxml using wheels? I don't think the cleaner uses anything from `libxml2`, but maybe something is different there...? Or maybe a different beautifulsoup4 version? I'm confused :)

**Comment by Ikke** [comment]
The problem is libxml2. The latest version (2.9.12) seems to cause issues, not just with this library. When I downgrade it to 2.9.10, then the output is as expected:

```
<div><strong>This is <em>a</em> message</strong></div>
```

So I'll close this issue as it's not a problem with this library.

For your info, this is on Alpine Linux, with packages from the repositories.

**Comment by Ikke** [comment]
Reference:

https://gitlab.gnome.org/GNOME/libxml2/-/issues/255
