### ISSUE TITLE
HTML entities are not preserved

### ISSUE THREAD

**Issue by mfostersyda** [matthiask/html-sanitizer#23]
Hi,

Love your package, but I can't seem to get it to preserve HTML entity references in the input thru to the output  (e.g. `&nbsp;` or `&rsquo;`) are returned as unicode chars not entity references even with keep_typographic_whitespace = True, and I don't see another option that disables this.  Re-HTML encoding the output translates tag characters like '<' and '>' into `&lt; `and `&gt;` which makes them inline characters and no longer tag markers in HTML.

I'm on:

python     3.10.4
lxml          4.9.1
bs4          4.11.1

Thanks!

**Comment by matthiask** [comment]
Thanks for the report! I'm wondering, why would you want to preserve the entities? I'll gladly look into it if I understand the reason :) or else you're welcome to contribute!

**Comment by mfostersyda** [comment]
Our use-case is migrating from a legacy CMS platform to WordPress, and have a separate DB of 20K use-contributed text that's been manually reviewed and edited, but as usual, some is cut and pasted from Word and other editors that have left a lot of CSS and other formatting cruft.  We want to clean that up as part of the migration, and rely solely on the enclosing page formatting going forward.  However, some formatting we want to preserve, so being able to designate tag types to preserve is perfect.  Because the text from this DB will be used in PHP functions via WP, and because we may still to do manual review/QA on entries in this DB, we want to preserve the HTML entities and not have it rendered yet into unicode.  Preserving whitespace is also important, because some creative contributors even did ascii art in their contributions, so preserving whitespace and `&nbsp;` entities is also important.

**Comment by matthiask** [comment]
Yes I understand, thanks. `lxml.html.HTMLParser` (https://lxml.de/4.0/api/lxml.html.HTMLParser-class.html) uses the etree HTMLParser under the hood and that one doesn't have the `resolve_entities=False` argument which we'd need for this. The `lxml.html.XHTMLParser` *does* support not resolving entities but then I get many many errors from the testsuite. I'm not sure if this is even doable with how things are right now. I also briefly checked if it would be possible to post-process the HTML and restore some of the more standard entities but I didn't find a library which does this. But maybe that would be a better way? It should be relatively straightforward to e.g. restore non-breaking spaces etc?

**Comment by mfostersyda** [comment]
`BeautifulSoup(sanitizer_output,'html.parser').prettify(formatter='html5')` comes closest, but inserts  newlines for readability.  I might be able to get by with this, pending further testing.  Thanks
