### ISSUE TITLE
sanitize_href

### ISSUE THREAD

**Issue by tvb** [matthiask/html-sanitizer#25]
Hi!

It is not clear to me how I call `sanitize_href` if I pass on my own settings.

```
from html_sanitizer import Sanitizer
sanitizer = Sanitizer({
    "tags": {
        "a", "h1", "h2", "h3", "strong", "em", "p", "ul", "ol",
        "li", "br", "sub", "sup", "hr",
    },
    "attributes": {"a": ("href", "name", "target", "title", "id", "rel")},
    "empty": {"hr", "a", "br"},
    "separate": {"a", "p", "li"},
    "whitespace": {"br"},
    "keep_typographic_whitespace": False,
    "add_nofollow": False,
    "autolink": False,
    "sanitize_href": sanitize_href,
    "element_preprocessors": [
        # convert span elements into em/strong if a matching style rule
        # has been found. strong has precedence, strong & em at the same
        # time is not supported
        bold_span_to_strong,
        italic_span_to_em,
        tag_replacer("b", "strong"),
        tag_replacer("i", "em"),
        tag_replacer("form", "p"),
        target_blank_noopener,
    ],
    "element_postprocessors": [],
    "is_mergeable": lambda e1, e2: True,
})
```

results in 
```
NameError: name 'sanitize_href' is not defined
```

Perhaps you can help clarify this in the documentation somewhat more?

**Comment by matthiask** [comment]
Hi 

You can either import `sanitize_href` (and all other methods) from the module where they are defined in (`html_sanitizer.sanitizer`) or take advantage of the fact that you do not have to specify configuration keys where the default configuration is good enough, see https://github.com/matthiask/html-sanitizer/blob/3fd32d3515af0926ecb68a04f4100a17c1d0a2f9/html_sanitizer/sanitizer.py#L169-L170

**Comment by tvb** [comment]
> Hi
> 
> You can either import `sanitize_href` (and all other methods) from the module where they are defined in (`html_sanitizer.sanitizer`) or take advantage of the fact that you do not have to specify configuration keys where the default configuration is good enough, see
> 
> https://github.com/matthiask/html-sanitizer/blob/3fd32d3515af0926ecb68a04f4100a17c1d0a2f9/html_sanitizer/sanitizer.py#L169-L170

So basically you are saying
```
sanitizer = Sanitizer({
    "tags": {
        "a",
        "h1",
        "h2",
        "h3",
        "strong",
        "em",
        "p",
        "ul",
        "ol",
        "li",
        "br",
        "sub",
        "sup",
        "hr",
        "s",
        "u"
    },
})
```
Is enough for me to support `<u>` and `<s>` tags?

**Comment by matthiask** [comment]
@tvb Yes, that should just work.

It's probably better to spell it out as you did but you could do even:

```python
from html_sanitizer import sanitizer
sanitizer = Sanitizer({"tags": sanitizer.DEFAULT_SETTINGS["tags"] | {"u"}})
```
HTML_SANITIZERS = {
    "default": {
        "tags": sanitizer.DEFAULT_SETTINGS["tags"] | {"u"},
    },
}
```

**Comment by tvb** [comment]
@matthiask Thanks for this! Would it make sense to clarify this somewhat more in the docs?

**Comment by matthiask** [comment]
Yes, sure. Do you want to submit a PR?

**Comment by tvb** [comment]
Sorry. I moved on. But thanks for the help.
