### ISSUE TITLE
Unable to import etree from lxml when running on arm64 architecture

### ISSUE THREAD

**Issue by tvb** [matthiask/html-sanitizer#26]
I am using AWS Lambda arm64 architecture for my Python code instead of the default x86_64 due to performance and pricing enhancements, but I get the following error:

```
Unable to import module 'index': cannot import name 'etree' from 'lxml' (/var/task/lxml/__init__.py)
```

Is this a known issue?

**Comment by matthiask** [comment]
That's a lxml issue, not a html-sanitizer issue. I'm not sure if the lxml devs know about this, but it seems to be somewhat known, see https://github.com/eerohele/sublime-lxml/issues/11 https://stackoverflow.com/questions/71737316/problems-installing-lxml-on-m1-mac

**Comment by tvb** [comment]
I see, does this mean html-sanitizer has a dependancy on lxml and it might need to be updated to support arm64?

**Comment by matthiask** [comment]
Yes; judging from the links it should be possible already to use lxml on arm64, but maybe precompiled packages do not exist already. I'm not sure though since I do not work on an arm64 machine (yet)

**Comment by tvb** [comment]
> Yes; judging from the links it should be possible already to use lxml on arm64, but maybe precompiled packages do not exist already. I'm not sure though since I do not work on an arm64 machine (yet)

If you want, you could run a AWS Lambda function on arm64 architecture to test.
