### ISSUE TITLE
Setting to allow repeated line breaks

### ISSUE THREAD

**Issue by pablopissi** [matthiask/html-sanitizer#29]
Hi! 
I was wondering if you would accept to create a setting to avoid the sanitization rule that removes repeated `<br>` tags.

Example:
`This is a text <br><br> two lines below`

becomes:
`This is a text <br> two lines below`

It does not seems to be insecure as <br> tags does not accept `href` or `class` attributes.
If you're ok with adding this setting, I can work on a PR

**Comment by matthiask** [comment]
Hi @pablopissi 

That's already possible, see

https://github.com/matthiask/html-sanitizer/blob/a9387ca9a2d3e57bc2d4a9ee44129f391ca24ad7/html_sanitizer/tests.py#L360-L371

You have to tell the sanitizer to keep `<br>` tags separate and not merge them.
