### ISSUE TITLE
Allow inline style preservation

### ISSUE THREAD

**Issue by jsonn** [matthiask/html-sanitizer#3]
I'd like to use html-sanitizer to post-process a richtext editor value. For my purposes, the inline style handling is at least somewhat necessary, i.e. for font size and alignment control at least. It would be nice to have a single post-processing hook before the second cleaner call and allow passing inline_style=true.

**Comment by matthiask** [comment]
Hmm. What we do in this case is the following (we use django-ckeditor, but the principle also applies to other editors):

We add custom styles to the Editor instance. The styles are applied using CSS classes:

```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'format_tags': 'h1;h2;h3;p;pre',
        'toolbar_Custom': [[
            'Styles', 'RemoveFormat', '-',
            'Bold', 'Italic', 'Subscript', 'Superscript', '-',
            'NumberedList', 'BulletedList', '-',
            'Anchor', 'Link', 'Unlink', '-',
            'HorizontalRule', 'SpecialChar', '-',
            'Source',
        ]],
        'stylesSet': [
            {'name': _('h1'), 'element': 'h1',
             'attributes': {'class': 'regular'}},
            {'name': _('h1 centered'), 'element': 'h1',
             'attributes': {'class': 'centered'}},
            {'name': _('h2'), 'element': 'h2',
             'attributes': {'class': 'regular'}},
            {'name': _('h2 centered'), 'element': 'h2',
             'attributes': {'class': 'centered'}},
            {'name': _('h3'), 'element': 'h3',
             'attributes': {'class': 'regular'}},
            {'name': _('h3 centered'), 'element': 'h3',
             'attributes': {'class': 'centered'}},
            {'name': _('paragraph'), 'element': 'p',
             'attributes': {'class': 'regular'}},
            {'name': _('paragraph centered'), 'element': 'p',
             'attributes': {'class': 'centered'}},
            {'name': _('paragraph two-columns'), 'element': 'p',
             'attributes': {'class': 'two-columns'}},
            {'name': _('button'), 'element': 'a',
             'attributes': {'class': 'button'}},
        ],
        'contentsCss': '/static/app/ckeditorstyles.css',
    },
}
```

Next, we allow `class` attributes on elements:

```
HTML_SANITIZERS = {
    'default': {
        'tags': {
            'a', 'h1', 'h2', 'h3', 'strong', 'em', 'p',
            'ul', 'ol', 'li', 'br', 'sub', 'sup', 'hr',
        },
        'attributes': {
            'a': ('href', 'name', 'target', 'title', 'id', 'class'),
            'p': ('class',),
            'h1': ('class',),
            'h2': ('class',),
            'h3': ('class',),
        },
        'empty': {'hr', 'a', 'br'},
        'separate': {'a', 'p', 'li'},
        # 'add_nofollow': False,
        # 'autolink': False,
        # 'element_filters': [],
        # 'sanitize_href': sanitize_href,
    },
}
```

This gives website editors additional tools, while still avoiding inline CSS completely. Would something like this work for you as well?

**Comment by jsonn** [comment]
I've been playing with going that route. It needs some more explicit CSS rules so that align attribute and alignment classes are handled correctly. The biggest problem right now is the [tag merging logic](https://github.com/matthiask/html-sanitizer/blob/cac93beb997838cc7ed5e25e6ebdd0ca7d981e5b/html_sanitizer/sanitizer.py#L232).  That will merge two consecutive lines with different alignment together. If class attributes are allowed and present, they should be honored?

**Comment by matthiask** [comment]
Ah yes, in this case the `separate` list should probably contain e.g. headings as well?

(The `separate` list above also contains the `p` tag for this reason.)

**Comment by jsonn** [comment]
Related question, would you support handling classes more like attributes, i.e. with a sanitizer dictionary of valid classes per tag?

**Comment by matthiask** [comment]
Except for `sanitize_href` we currently do not handle attribute contents at all. 

I can very well imagine that the attributes' contents is passed through an additional function similar to `sanitize_href`. I'm not sure about ad-hoc specifications of contents such as a list of allowed classes.

**Comment by jsonn** [comment]
OK, class-based filtering works well enough for now.
