### ISSUE TITLE
Updating from 2.0.0 to 2.1.0 issue on settings declaration.

### ISSUE THREAD

**Issue by xHaddocK** [matthiask/html-sanitizer#30]
After the update to 2.1.0 I got an error when leaving whitespace (i guess) set empty:

```
DEFAULT_SETTINGS = {
    "tags": {"h1", "h2", "h3", "b", "strong", "em", "p", "ul", "ol", "li", "br", "sub", "sup", "hr"},
    "attributes": {},
    "empty": {"hr", "br"},
    "separate": {"p", "li", "br"},
    "whitespace": {},
    "keep_typographic_whitespace": False,
    "add_nofollow": False,
    "autolink": False,
    "element_preprocessors": [
        tag_replacer('h4', 'h3'),
        tag_replacer('h5', 'h3'),
        tag_replacer('h6', 'h3')
    ],
    "element_postprocessors": []
}
```

The error is: `TypeError: Expected a set but got value {} of type <class 'dict'>`

The trace error is: 
```
File "/var/task/main.py", line 61, in <module>
    sanitizer = Sanitizer(DEFAULT_SETTINGS)
  File "/var/task/html_sanitizer/sanitizer.py", line 193, in __init__
    self.whitespace = coerce_to_set(self.whitespace)
  File "/var/task/html_sanitizer/sanitizer.py", line 181, in coerce_to_set
    raise TypeError(f"Expected a set but got value {value!r} of type {type(value)}")
```

Resetting the version to 2.0.0 will fix the problem.

**Comment by matthiask** [comment]
Yes, I'm sorry for that. I thought that it would be better to be overzealous when validating settings because I encountered `("class")` instead of `{"class"}` in one of our projects.

`whitespace` is supposed to be a set of tag names; you have a dictionary there. You should change your settings to `"whitespace": set()` or maybe `"whitespace": []`.

**Comment by xHaddocK** [comment]
Thank you for your quick answer, now the sanitizer is working as nice as always!
