### ISSUE TITLE
Merging tags inserts a space between them

### ISSUE THREAD

**Issue by rob-3** [matthiask/html-sanitizer#35]
Hi - thanks for all your work on the project!

I've been having an issue where tag merging inserts a space in between:
```py
# fails
def test_no_space_between_same_tags(self):
    entries = [("<strong>Hel</strong><strong>lo</strong>", "<strong>Hello</strong>")]
    # actual: "<strong>Hel lo</strong>"
    # notice space here   ^
    self.run_tests(entries)
```

I have a patch that fixes this locally, but I'm not sure if you would accept it as is, since it changes the behavior in a not-necessarily-compatible way. Maybe this behavior could go behind a flag if it can't become the default?

**Comment by matthiask** [comment]
Hey

Do the tests still pass? Or maybe asked differently, do the changes to the testsuite make sense to you?

It seems to me that the change should make sense since the "before" version doesn't have any whitespace either.
