### ISSUE TITLE
bug from dependency

### ISSUE THREAD

**Issue by wdxwj** [matthiask/html-sanitizer#43]
Please don't use >=
When I use html-sanitizer==2.2.0  the lxml is using 5.x.x and I get ImportError: cannot import name 'Sanitizer' from 'html_sanitizer' (/usr/local/lib/python3.11/site-packages/html_sanitizer/__init__.py)
when I use lxml==4.9.3 , it works well.

dependencies = [
  "beautifulsoup4",
  "lxml>=5.2.0",
  "lxml-html-clean>=0.1.0",
]

**Comment by matthiask** [comment]
What happens when you upgrade to `html-sanitizer==2.4.1`?

Using `>=` has worked well for me for many years now. I don't want to restrict people from installing newer versions of dependencies because some of them contain security fixes and it would be very annoying to prevent people from using better versions of dependencies. The work required to bump upper limits is just too great.

**Comment by wdxwj** [comment]
> What happens when you upgrade to `html-sanitizer==2.4.1`?
> 
> Using `>=` has worked well for me for many years now. I don't want to restrict people from installing newer versions of dependencies because some of them contain security fixes and it would be very annoying to prevent people from using better versions of dependencies. The work required to bump upper limits is just too great.

the newest version of html-sanitizer is good for me. Thanks a lot. But I think always using newest version may bring potential bugs.

**Comment by matthiask** [comment]
> But I think always using newest version may bring potential bugs.

Yes, that's of course a concern. But it's a concern which can be worked around in a project by pinning the dependency to a lower version. OTOH if I were to restrict the upper range of allowed versions you couldn't do that as an user. I'd have to release new patch releases when a security release of lxml (or whatever) drops and that sounds like the worse end of the trade off to me.

Thank you!
