### ISSUE TITLE
Only want to remove the script tag.

### ISSUE THREAD

**Issue by vishalzillion** [matthiask/html-sanitizer#45]
so i want to use all the html tags and their attributes except script tag, but for this i need to add all the tags and attributes in default settings. is there a way through which i did not need to do that

**Comment by matthiask** [comment]
Maybe https://github.com/messense/nh3 would work better for you since it only sanitizes and doesn't do additional, more opinionated cleanups?

**Comment by vishalzillion** [comment]
okay will check that,
thank you.
