### ISSUE TITLE
lxml-html-clean dependency high severity vulnerability

### ISSUE THREAD

**Issue by KeeperFrancis** [matthiask/html-sanitizer#50]
Hello,
Is it possible to update the dependency package `lxml-html-clean` to  `>=0.4.0` ?
Dependabot marks it as 7.7/10 high severity vulnerability

![2024-12-18 20_22_26-Window](https://github.com/user-attachments/assets/0dbfebc1-6460-4da6-9f2d-ab400ed79437)
![2024-12-18 20_23_01-Window](https://github.com/user-attachments/assets/030b8c17-e61c-4d29-9162-c97da33a311a)
Thanks

**Comment by KeeperFrancis** [comment]
Nevermind just see it's "lxml-html-clean>=0.1"
the new version probably can be used.
Thanks

**Comment by matthiask** [comment]
Thanks for the heads up! Yes, we were compatible already, and I generally don't use upper bounds for versions. Raising the lower bound still makes sense, and I have just released 2.5 containing this change.
