### ISSUE TITLE
White-space normalisation and preserved tags

### ISSUE THREAD

**Issue by jsonn** [matthiask/html-sanitizer#7]
The current white-space logic will normalize leading and trailing white-space to a single character. That's fine. But it fully removes the white-space if a tag contains only spaces. This breaks the separation if the tag is not going to be removed, i.e.
```
1<a> </a>2
```
is semantically and visually quite different from
```
1<a></a>2
```
I'm filling this as issue and not a PR since a fix seems somewhat intrusive and I'd like to discuss the problem first.

**Comment by matthiask** [comment]
Oh right, that's bad behavior. We (I?) should fix this.

**Comment by matthiask** [comment]
@jsonn It wasn't as invasive as I thought it would be: https://github.com/matthiask/html-sanitizer/commit/aa7378d44e3603cdfa911d1e14e344891dac48c9  -- does this look right to you?

**Comment by matthiask** [comment]
This issue has been fixed by various commits in the past few days. It's probably still not perfect, but at least the whitespace in the example is preserved.
