### ISSUE TITLE
Any way to completely remove all html tags?

### ISSUE THREAD

**Issue by brandonsturgeon** [matthiask/html-sanitizer#8]
Currently when I initialize the sanitizer like this:
```py
sanitizer = Sanitizer({"tags": set(), "attributes": {}, "empty": set(), "separate": set()})
```

and sanitize like this:
```py
sanitizer.sanitize('<span style="color:#000;font-weight:bold;font-size:6pt">11:44:14</span>')
```

I get this:
```py
'<strong>11:44:14</strong>'
```

I just want all tags gone, is there any way to do that with this tool?

**Comment by matthiask** [comment]
Hmm, so the lxml cleaner does not support removing all tags; an empty list of tags is equivalent to not dropping any tags at all:
https://github.com/lxml/lxml/blob/396ded1558c4ea7a3723be994c76304b7c5edff8/src/lxml/html/clean.py#L403

What you can do is initialize the sanitizer with `Sanitizer({"tags": {"will_hopefully_never_exist_in_the_doc"}, ...})` and it will do what you want.

**Comment by brandonsturgeon** [comment]
Thank you!
