### ISSUE TITLE
Multiple br tags in a row

### ISSUE THREAD

**Issue by vryazanov** [matthiask/html-sanitizer#9]
Hi there,
I'm looking for a way not to remove multiple `br` tags in a row.
Now I see only one way, comment this block: https://github.com/matthiask/html-sanitizer/blob/master/html_sanitizer/sanitizer.py#L262

does it have more elegant solution?

**Comment by matthiask** [comment]
There wasn't, but now there is one:
https://github.com/matthiask/html-sanitizer/blob/d1abac07e283ff1c638808d46116bbc49ec99b48/html_sanitizer/tests.py#L342-L353
